Don't use immature outputs when funding a transaction
SiaFoundation/coreutils pull request #24
Opened 2024-02-21 15:14 UTC by peterjan

2024-02-21 16:23 UTC, n8maninger requested changes

2024-02-21 16:23 UTC, n8maninger commented on wallet/wallet.go
> +	filtered := elements[:0]
This should be added to the existing loop on line 311

2024-02-21 19:31 UTC, n8maninger approved these changes

2024-02-22 08:24 UTC, ChrisSchinnerl approved these changes

2024-02-22 08:24 UTC, merged